name: loscat-vit
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - pip
  - pip:
      - timm>=0.9.8
      - pandas>=2.0
      - numpy>=1.23
      - pillow>=10.0
      - matplotlib>=3.7
      - seaborn>=0.12
      - scikit-learn>=1.3
      - huggingface_hub>=0.23
